/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StudyAbroadConsultancySoftwareRouteImport } from './routes/study-abroad-consultancy-software'
import { Route as ApiPublicBgImageRouteImport } from './routes/api/public/bg-image'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyAbroadConsultancySoftwareRoute =
  StudyAbroadConsultancySoftwareRouteImport.update({
    id: '/study-abroad-consultancy-software',
    path: '/study-abroad-consultancy-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBgImageRoute = ApiPublicBgImageRouteImport.update({
  id: '/api/public/bg-image',
  path: '/api/public/bg-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-abroad-consultancy-software': typeof StudyAbroadConsultancySoftwareRoute
  '/api/public/bg-image': typeof ApiPublicBgImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-abroad-consultancy-software': typeof StudyAbroadConsultancySoftwareRoute
  '/api/public/bg-image': typeof ApiPublicBgImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-abroad-consultancy-software': typeof StudyAbroadConsultancySoftwareRoute
  '/api/public/bg-image': typeof ApiPublicBgImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/study-abroad-consultancy-software'
    | '/api/public/bg-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/study-abroad-consultancy-software'
    | '/api/public/bg-image'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/study-abroad-consultancy-software'
    | '/api/public/bg-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudyAbroadConsultancySoftwareRoute: typeof StudyAbroadConsultancySoftwareRoute
  ApiPublicBgImageRoute: typeof ApiPublicBgImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-abroad-consultancy-software': {
      id: '/study-abroad-consultancy-software'
      path: '/study-abroad-consultancy-software'
      fullPath: '/study-abroad-consultancy-software'
      preLoaderRoute: typeof StudyAbroadConsultancySoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bg-image': {
      id: '/api/public/bg-image'
      path: '/api/public/bg-image'
      fullPath: '/api/public/bg-image'
      preLoaderRoute: typeof ApiPublicBgImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudyAbroadConsultancySoftwareRoute: StudyAbroadConsultancySoftwareRoute,
  ApiPublicBgImageRoute: ApiPublicBgImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
